### ISSUE TITLE
Nicht der einzige 

### ISSUE THREAD

**Issue by muessjoeh** [JochenDiekenbrock/wuerfelschlange#1]
Hallo!

Du warst übrigens nicht der einzige, der die Idee hatte, das in Software nachzubauen. Meinen Ansatz kann man unter https://gitlab.com/muessjoeh/w-rfelschlange ansehen. Direkt im Browser kann es allerdings nicht laufen. 

Christian

**Comment by JochenDiekenbrock** [comment]
Hi Christian,

offensichtlich ein inspirierendes Thema :-)

---
Gruß, Jochen

Am 10.03.2020 08:45, schrieb muessjoeh:
